### ISSUE TITLE
Fix the automatic publishing on NPM

### ISSUE THREAD

**Issue by katspaugh** [wavesurfer-js/wavesurfer.js#2723]
The script that published the NPM package is broken after #2710.

https://github.com/wavesurfer-js/wavesurfer.js/actions/runs/4419688300/jobs/7748430370

Looks like this part was necessary after all:

```
      - uses: actions/setup-node@v3
         with:
           node-version: 16
           registry-url: https://registry.npmjs.org/
```
